package com.projects.designpatterns.creational.enums;

public enum Sauce {
    MAYONNAISE_SAUCE,
    MINT_MAYONNAISE_SAUCE,
    CHIPOTLE_SOUTH_WEST_SAUCE,
    HONEY_MUSTARD_SAUCE,
    RED_CHILLI_SAUCE,
    MARINARA_SAUCE_NEW,
    BARBEQUE_SAUCE,
    TANDOORI_MAYO_SAUCE_NEW,
    SWEET_ONION_SAUCE
}
